version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        root_path: /
        api_port: 5000
    image: bot-detector/bd-api-temp:latest
    ports:
      - 5000:5000
    networks:
      - botdetector-network
      
networks:
  botdetector-network:
